---  ═══════════════════════════════════════════════════════════════════════════
---   GEO Movement Management Module
---  ═══════════════════════════════════════════════════════════════════════════
---   Nothing GEO-specific: AutoMove tracks movement for every job
---   (INIT_SYSTEMS) and the GEO set builder lays the speed gear. The file
---   stays for the 12-module layout.
---
---   @file    shared/jobs/geo/functions/GEO_MOVEMENT.lua
---   @author  ejouanchicot
---   @version 1.0
---   @date    Created: 2025-10-09
---   @requires shared/utils/movement/automove.lua
---  ═══════════════════════════════════════════════════════════════════════════

