sets.exported={
    main="Naegling",
    sub={ name="Demers. Degen +1", augments={'Path: A',}},
    range="Gjallarhorn",
    head="Aya. Zucchetto +2",
    body="Ayanmo Corazza +2",
    hands={ name="Bunzi's Gloves", augments={'Path: A',}},
    legs="Fili Rhingrave +3",
    feet="Fili Cothurnes +3",
    neck={ name="Bard's Charm +2", augments={'Path: A',}},
    waist={ name="Sailfi Belt +1", augments={'Path: A',}},
    left_ear="Dedition Earring",
    right_ear="Telos Earring",
    left_ring="Moonlight Ring",
    right_ring="Moonlight Ring",
    back={ name="Intarabus's Cape", augments={'DEX+20','Accuracy+20 Attack+20','DEX+10','"Store TP"+10','Phys. dmg. taken-10%',}},
}