-- GENERATED by scripts/item_db/build_fast_cast_db.py - do not edit by hand.
-- Fast Cast (percent) of the pieces whose game text gives no number for it
-- (Enhances "Fast Cast" effect), by item id. Values from BG-Wiki through the
-- Atelier catalogue. Read by shared/utils/precast/cast_time.lua, added to what
-- it reads in the description.
return {
[10326]=8, -- Enif Cosciales
[10365]=4, -- Chelona Boots
[10366]=5, -- Chelona Boots +1
[10394]=5, -- Orunmila's Torque
[10469]=10, -- Eirene's Manteel
[10514]=2, -- Magavan Mitts
[10517]=2, -- Repartie Gloves
[10528]=4, -- Thaumas Gloves
[10674]=12, -- Dls. Tabard +2
[10749]=5, -- Argute Loafers +2
[10752]=2, -- Prolix Ring
[10802]=5, -- Majorelle Shield
[10826]=3, -- Witful Belt
[10877]=2, -- Athos's Chapeau
[10910]=7, -- Tethyan Cap +3
[10911]=10, -- Nares Cap
[10913]=10, -- Hyaline Hat
[11000]=3, -- Swith Cape
[11001]=4, -- Swith Cape +1
[11070]=5, -- Creed Armet +2
[11544]=1, -- Veela Cape
[11615]=5, -- Orison Locket
[11707]=2, -- Estq. Earring
[11849]=5, -- Nebula Hpl. +1
[11856]=10, -- Anhur Robe
[11916]=1, -- Nebula Cuffs +1
[11955]=2, -- Nebula Slops +1
[12132]=2, -- Ebon Tam
[12133]=2, -- Furia Tam
[12134]=2, -- Ebur Tam
[12170]=5, -- Ebur Talar
[12513]=10, -- Warlock's Chapeau
[13001]=3, -- Augur's Gaiters
[14504]=11, -- Dls. Tabard +1
[14812]=2, -- Loquac. Earring
[15091]=10, -- Duelist's Tabard
[15229]=10, -- Wlk. Chapeau +1
[15350]=3, -- Rostrum Pumps
[15576]=5, -- Homam Cosciales
[17079]=2, -- Winged Wand
[18557]=10, -- Sortilege Scythe
[18897]=5, -- Isador
[19049]=1, -- Vivid Strap
[19051]=1, -- Vivid Strap +1
[19257]=2, -- Incantor Stone
[19282]=10, -- Hochomasamune
[21201]=2, -- Atinian Staff +1
[24340]=5, -- Egbesu Mitts
[27667]=11, -- Atrophy Chapeau
[27768]=5, -- Cizin Helm
[27775]=10, -- Nahtirah Hat
[27787]=10, -- Runeist Bandeau
[27791]=11, -- Marduk's Jubbah +1
[27963]=5, -- Acad. Bracers
[28054]=7, -- Gendewitha Gages
[28080]=5, -- Fea's Slops
[28085]=1, -- Neit's Slops
[28184]=5, -- Orvail Pants +1
[28203]=5, -- Orvail Pants
[28206]=10, -- Geomancy Pants
[28216]=4, -- Nabu's Crackows
[28637]=7, -- Lifestream Cape
}
