"""Builds atelier/calc/calc_ws_table.js from our weapon skill database.

Reads shared/data/weaponskills/<SKILL>_WS_DATABASE.lua (taken from BG-Wiki) and writes, for every
weapon skill, what the calculation engine reads: the combat skill, the type (Physical, Magical,
Hybrid, None), the attribute modifiers in percent, the number of hits, the element and the fTP at
1000 / 2000 / 3000 TP. Nothing is added or corrected here: what the database lacks or gets wrong
is in atelier/calc/calc_ws_details.js, read on each weapon skill's BG-Wiki page.

    python scripts/atelier/build_ws_table.py

@file    scripts/atelier/build_ws_table.py
@author  ejouanchicot
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "shared" / "data" / "weaponskills"
TARGET = ROOT / "atelier" / "calc" / "calc_ws_table.js"

# file name -> combat skill, as the gear names it ("Skill Type" of a weapon)
SKILLS = {
    "ARCHERY": "Archery", "AXE": "Axe", "CLUB": "Club", "DAGGER": "Dagger", "GREATAXE": "Great Axe",
    "GREATKATANA": "Great Katana", "GREATSWORD": "Great Sword", "H2H": "Hand-to-Hand",
    "KATANA": "Katana", "POLEARM": "Polearm", "SCYTHE": "Scythe", "STAFF": "Staff", "SWORD": "Sword",
}

ENTRY = re.compile(r"^    \[(['\"])(.+?)\1\]\s*=\s*\{(.*?)^    \},?", re.S | re.M)


def field(body, name):
    """Text of one `name = value` line of an entry, without its trailing comment."""
    found = re.search(r"^\s*" + name + r"\s*=\s*(.+?)\s*$", body, re.M)
    if not found:
        return None
    return re.sub(r",?\s*(--.*)?$", "", found.group(1))


def pairs(text, key_pattern):
    """{key = number, ...} of a Lua table written on one line."""
    return {k: float(v) for k, v in re.findall(key_pattern + r"\s*=\s*(-?[\d.]+)", text or "")}


def modifiers(body):
    """Attribute modifiers in percent: `mods = {STR = 60}` or `stat_modifiers = "40% DEX / 40% INT"`."""
    mods = pairs(field(body, "mods"), r"([A-Z]{3})")
    text = field(body, "stat_modifiers")
    if text and not mods:
        mods = {attr: float(pct) for pct, attr in re.findall(r"([\d.]+)%\s*([A-Z]{3})", text)}
    return mods


def from_notes(body):
    """Hits and fTP of the entries that only have them in a `notes` sentence (the dagger file):
    "5 hits, ...", "fTP 4.5/6.8/8.5", "fTP 5.0"."""
    notes = field(body, "notes") or ""
    hits = re.search(r"(\d+) hits?(?![a-z])", notes)
    ftp = re.search(r"fTP ([\d.]+(?:/[\d.]+)*)", notes)
    values = [float(v) for v in ftp.group(1).split("/")] if ftp else None
    if values and len(values) == 1:
        values = values * 3
    return (hits.group(1) if hits else None), (values if values and len(values) == 3 else None)


def read_entry(skill, name, body):
    ftp = pairs(field(body, "ftp"), r"\[(\d+)\]")
    hits = field(body, "hits")
    noted_hits, noted_ftp = from_notes(body)
    hits = hits or noted_hits
    element = field(body, "element")
    kind = field(body, "type")
    entry = {"skill": skill, "type": kind.strip("'\"") if kind else None, "mods": modifiers(body)}
    entry["hits"] = int(hits) if hits and hits.isdigit() else None
    entry["element"] = None if element in (None, "nil") else element.strip("'\"")
    entry["ftp"] = [ftp.get(str(tp)) for tp in (1000, 2000, 3000)] if ftp else noted_ftp
    return entry


def read_database():
    table = {}
    for path in sorted(SOURCE.glob("*_WS_DATABASE.lua")):
        skill = SKILLS.get(path.name.split("_")[0])
        if not skill:
            continue
        for _, name, body in ENTRY.findall(path.read_text(encoding="utf-8")):
            name = name.replace("\\'", "'")  # ['Rudra\'s Storm'] in the Lua source
            table[name] = read_entry(skill, name, body)
    return table


def main():
    table = read_database()
    lines = ["    %s: %s" % (json.dumps(name), json.dumps(table[name], sort_keys=True)) for name in sorted(table)]
    TARGET.write_text(
        "// Atelier calculation engine, stage 2: the weapon skills of our database.\n"
        "// GENERATED by scripts/atelier/build_ws_table.py from shared/data/weaponskills/*.lua\n"
        "// (source of that database: BG-Wiki). Do not edit: change the database and run the script.\n"
        "// mods are percents of the attribute, ftp is [at 1000 TP, at 2000, at 3000];\n"
        "// null = the database does not say.\n"
        "//\n"
        "// @file    atelier/calc/calc_ws_table.js\n"
        "// @author  ejouanchicot\n"
        "(globalThis.CALC_PARTS = globalThis.CALC_PARTS || []).push(function (CALC) {\n"
        "    CALC.WS_TABLE = {\n" + ",\n".join(lines) + "\n    };\n});\n",
        encoding="utf-8", newline="\n")
    print("%d weapon skills written to %s" % (len(table), TARGET.relative_to(ROOT)))


if __name__ == "__main__":
    main()
