// Writes atelier/lua/lua51.js: Lua 5.1.5 compiled to WebAssembly, in the one form the Atelier page can load.
//
//   node scripts/atelier/build_lua_wasm.js <folder holding node_modules/lua-wasm-bindings>
//   (get it with: npm install lua-wasm-bindings@0.5.3, in any folder)
//
// The page is opened from the disk (file://): a browser lets it load a script, not fetch a .wasm file nor start a
// worker from a file. So both parts of the build go into one script as text: the loader's source (the worker
// evaluates it) and the binary in base64. The loader keeps its in-memory file system to itself: one line is added
// so the page can put the job files in it.
//
// Lua 5.1.5: Copyright (C) 1994-2012 Lua.org, PUC-Rio, MIT license.
// The WebAssembly build: lua-wasm-bindings 0.5.3, Lorenz Junglas (TypeScriptToLua), MIT license,
// https://github.com/TypeScriptToLua/lua-wasm-bindings
//
// @author ejouanchicot
// @date   Created: 2026-10-08
const fs = require('fs'), path = require('path');
const from = path.join(process.argv[2] || '.', 'node_modules/lua-wasm-bindings/dist/glue');
const src = fs.readFileSync(path.join(from, 'glue-lua-5.1.5.js'), 'utf8');
const glue = src.replace('Module["cwrap"]=cwrap', 'Module["cwrap"]=cwrap;Module["FS"]=FS');
if (glue === src) throw new Error('the loader changed: the line that hands out its file system was not found');
const wasm = fs.readFileSync(path.join(from, 'glue-lua-5.1.5.wasm')).toString('base64');
const out = path.join(__dirname, '../../atelier/lua/lua51.js');
fs.mkdirSync(path.dirname(out), {recursive: true});
fs.writeFileSync(out,
  '// Lua 5.1.5 compiled to WebAssembly, for the Atelier page\'s export without the game (atelier/app/js/offline_export.js).\n' +
  '// GENERATED by scripts/atelier/build_lua_wasm.js: do not edit.\n' +
  '// Lua 5.1.5: Copyright (C) 1994-2012 Lua.org, PUC-Rio, MIT license (https://www.lua.org/license.html).\n' +
  '// WebAssembly build: lua-wasm-bindings 0.5.3, Lorenz Junglas (TypeScriptToLua), MIT license.\n' +
  '(typeof window !== "undefined" ? window : globalThis).ATELIER_LUA = {\n' +
  'glue: ' + JSON.stringify(glue) + ',\n' +
  'wasm: "' + wasm + '"};\n');
console.log(out, Math.round(fs.statSync(out).size / 1024) + ' KB');
