-- Generated by the dead-code scan (2026-10-01): the functions the scan
-- finds unused, watched by //gs c tombstones (shared/utils/debug/tombstones.lua).
-- {module, table, function, file, line}. Delete with the dead code.
return {
}
