"""Fast Cast the game text does not give in numbers -> shared/data/equipment/ITEM_FAST_CAST.lua

Many pieces only say: Enhances "Fast Cast" effect. Their value comes from the Atelier catalogue
(atelier/engine/catalog/items.json, itself read from BG-Wiki for those hidden values). A piece is
written only when the catalogue holds more Fast Cast than shared/utils/precast/cast_time.lua reads
in its description, and only the difference is written.

    python scripts/item_db/build_fast_cast_db.py [--res <Windower res folder>]
"""
import io
import json
import os
import re
import sys

DATA = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..'))
RES = os.path.normpath(os.path.join(DATA, '..', '..', '..', 'res'))
if '--res' in sys.argv:
    RES = sys.argv[sys.argv.index('--res') + 1]
CATALOG = os.path.join(DATA, 'atelier', 'engine', 'catalog', 'items.json')
OUT = os.path.join(DATA, 'shared', 'data', 'equipment', 'ITEM_FAST_CAST.lua')

ENTRY = re.compile(r'\[(\d+)\] = \{id=\d+,en="((?:[^"\\]|\\.)*)"')


def read_fast_cast(description):
    """Same reading as reduction_in() of cast_time.lua, Fast Cast only."""
    text = re.sub(r'[Ss]et:.*', '', description.replace('\\n', ' ').replace('\\"', '"'), flags=re.S).lower()
    return sum(int(n) for n in re.findall(r'"fast cast"\s*\+\s*(\d+)', text))


def main():
    descs = {int(m.group(1)): m.group(2) for m in ENTRY.finditer(
        io.open(os.path.join(RES, 'item_descriptions.lua'), encoding='utf-8').read())}
    catalog = json.load(io.open(CATALOG, encoding='utf-8'))['items']
    rows = []
    for item in (catalog.values() if isinstance(catalog, dict) else catalog):
        total = (item.get('stats') or {}).get('Fast Cast')
        if not isinstance(total, (int, float)) or total <= 0:
            continue
        hidden = total - read_fast_cast(descs.get(item['id'], ''))
        if hidden > 0:
            rows.append((item['id'], int(hidden), item['name']))
    rows.sort()
    lines = [
        '-- GENERATED by scripts/item_db/build_fast_cast_db.py - do not edit by hand.',
        '-- Fast Cast (percent) of the pieces whose game text gives no number for it',
        '-- (Enhances "Fast Cast" effect), by item id. Values from BG-Wiki through the',
        '-- Atelier catalogue. Read by shared/utils/precast/cast_time.lua, added to what',
        '-- it reads in the description.',
        'return {',
    ]
    lines += ['[%d]=%d, -- %s' % row for row in rows]
    lines.append('}')
    io.open(OUT, 'w', encoding='utf-8', newline='\n').write('\n'.join(lines) + '\n')
    print('%d pieces -> %s' % (len(rows), os.path.relpath(OUT, DATA)))


if __name__ == '__main__':
    main()
