---  ═══════════════════════════════════════════════════════════════════════════
---   Message Display Modes - Auto-Generated Persistent Settings
---  ═══════════════════════════════════════════════════════════════════════════
---   Persistent message mode settings for all message types.
---   This file is automatically managed by message_settings.lua
---
---   Modes:
---     • spell_mode: ALL spell types (Enhancing, Enfeebling, Healing, Elemental)
---     • ja_mode: Job Abilities
---     • ws_mode: Weapon Skills
---
---   Valid Values:
---     • 'full' - Show name + description
---     • 'on'   - Show name only
---     • 'off'  - Silent (no messages)
---
---   @file    shared/config/message_modes.lua
---   @author  Auto-Generated by MessageSettings
---   @version 2.0 - Per-character persistence
---   @date    Updated: 2025-11-12
---  ═══════════════════════════════════════════════════════════════════════════

return {
    spell_mode = 'on',    -- Spells: name only
    ja_mode = 'full',     -- Job Abilities: name + description
    ws_mode = 'on'        -- Weapon Skills: name + TP only
}
