---  ═══════════════════════════════════════════════════════════════════════════
---   Wardrobe Organizer - Warp items this character actually owns
---  ═══════════════════════════════════════════════════════════════════════════
---   The warp database lists every ring and cape the warp system knows about -
---   65 of them. A character owns a handful. Keeping all 65 out of overflow
---   costs nothing in slots (the organizer only moves what it finds), but it
---   makes `//gs c wo keep` unreadable and hides which ones are really at
---   stake.
---
---   `//gs c wo scan` walks every bag, keeps the intersection, and writes it to
---   data/<char>/config/WARP_ITEMS_OWNED.lua. The organizer prefers that list
---   when it exists and falls back to the full database when it does not, so a
---   character who never scans behaves exactly as before.
---
---   Re-run it after acquiring or discarding a ring. Nothing else updates it:
---   guessing from an empty bag would silently drop an item that is merely in
---   a Mog Safe at the time.
---
---   @file shared/utils/wardrobe/lib/warp_owned.lua
---   @author Tetsouo
---  ═══════════════════════════════════════════════════════════════════════════

local res = require('resources')

local WarpOwned = {}

--- @return string|nil Absolute path of this character's owned-items file
function WarpOwned.path()
    local p = windower.ffxi.get_player()
    if not p or not p.name then return nil end
    return windower.addon_path .. 'data/' .. p.name .. '/config/WARP_ITEMS_OWNED.lua'
end

--- @return table|nil Array of item names, nil when the file is absent/unreadable
function WarpOwned.load()
    local path = WarpOwned.path()
    if not path or not windower.file_exists(path) then return nil end
    local ok, list = pcall(dofile, path)
    if not ok or type(list) ~= 'table' then return nil end
    return list
end

--- Every warp item found in any bag, storage included.
---
--- Storage counts on purpose: a ring in the Mog Safe is still owned, and the
--- point of the list is "what may turn up in a wardrobe one day", not "what is
--- reachable this second".
--- @return table Array of item names, sorted
--- @return number How many the warp database knows in total
function WarpOwned.scan()
    local known = {}
    local total = 0

    local ok, WarpDatabase = pcall(require, 'shared/utils/warp/database/warp_database_core')
    if ok and WarpDatabase and WarpDatabase.get_all_item_names then
        for _, name in ipairs(WarpDatabase.get_all_item_names()) do
            known[name:lower()] = name
            total = total + 1
        end
    end
    if total == 0 then return {}, 0 end

    local found, seen = {}, {}
    local items = windower.ffxi.get_items()
    if items then
        for bag_id in pairs(res.bags) do
            local bag = items[res.bags[bag_id].api]
            if type(bag) == 'table' then
                for _, entry in pairs(bag) do
                    local id = type(entry) == 'table' and entry.id or nil
                    local data = id and id > 0 and res.items[id]
                    local name = data and data.en
                    local real = name and known[name:lower()]
                    if real and not seen[real] then
                        seen[real] = true
                        found[#found + 1] = real
                    end
                end
            end
        end
    end

    table.sort(found)
    return found, total
end

--- Write the list so the organizer picks it up on its next run.
--- @param names table Array of item names
--- @return string|nil Path written, nil on failure
--- @return string|nil Reason it could not be written
function WarpOwned.save(names)
    local path = WarpOwned.path()
    if not path then return nil, 'no player' end

    local file, err = io.open(path, 'w')
    if not file then return nil, tostring(err) end

    file:write('---  Warp items this character owns - generated by //gs c wo scan\n')
    file:write('---  Re-run that command after acquiring or discarding one.\n')
    file:write('---  Delete this file to fall back on the full warp database.\n')
    file:write('return {\n')
    for _, name in ipairs(names) do
        file:write(string.format('    %q,\n', name))
    end
    file:write('}\n')
    file:close()

    return path
end

return WarpOwned
