---  ═══════════════════════════════════════════════════════════════════════════
---   THF Movement Management Module - Movement Detection & Speed Gear
---  ═══════════════════════════════════════════════════════════════════════════
---   Handles movement-based equipment optimization for Thief using centralized
---   AutoMove position tracking for performance.
---
---   Nothing THF-specific: AutoMove tracks movement for every job
---   (INIT_SYSTEMS) and logic/set_builder.lua lays the speed gear (idle only).
---   The file stays for the 12-module layout.
---
---   Dependencies:
---   • AutoMove (centralized movement tracking system)
---
---   @file    shared/jobs/thf/functions/THF_MOVEMENT.lua
---   @author  ejouanchicot
---   @version 1.0
---   @date    Created: 2025-10-06
---  ═══════════════════════════════════════════════════════════════════════════
