---  ═══════════════════════════════════════════════════════════════════════════
---   DNC Movement Management Module
---  ═══════════════════════════════════════════════════════════════════════════
---   Nothing DNC-specific: AutoMove tracks movement for every job
---   (INIT_SYSTEMS) and the set builder lays the speed gear. The file stays
---   for the 12-module layout.
---
---   @file    shared/jobs/dnc/functions/DNC_MOVEMENT.lua
---   @author  ejouanchicot
---   @version 1.0
---   @date    Created: 2025-10-04
---  ═══════════════════════════════════════════════════════════════════════════

