---============================================================================
--- BLU Alt Commands - what the alt does when it is on BLU
---============================================================================
--- Read by shared/utils/dualbox/alt_commands.lua, whether BLU is the alt's
--- MAIN job or its SUBJOB. Type the key on the MAIN and the alt performs it.
---
--- GENERATED - do not edit. Put your changes in BLU_ALT_CUSTOM.lua, which is
--- merged on top of this file and never regenerated.
---
--- Sources: the project's own data decides what exists and at which level
--- (shared/data/job_abilities/ and shared/data/magic/), res/spells.lua and
--- res/job_abilities.lua supply targeting.
---
--- Abilities carry `level`, spells carry every tier with the level it needs.
--- The engine picks the highest the alt is high enough for, from the level it
--- reported - a subjob caps far below a main (Master Level 50 reaches sub 58).
--- `main_only` entries disappear entirely when the job is the subjob.
---
--- @file    config/alt/BLU_ALT_COMMANDS.lua
--- @author  Tetsouo
--- @version 1.0
--- @date    Created: 2026-08-09
---============================================================================

local M = {}

M.commands = {
    -- ========================================================================
    -- JOB ABILITIES
    -- ========================================================================
    azurelore        = { action = 'ja', spell = 'Azure Lore',             target = 'me', level = 1, main_only = true, group = 'ja', desc = 'Blue magic enhanced' },
    burstaffinity    = { action = 'ja', spell = 'Burst Affinity',         target = 'me', level = 25, group = 'ja', desc = 'Magical blue magic can magic burst' },
    chainaffinity    = { action = 'ja', spell = 'Chain Affinity',         target = 'me', level = 40, group = 'ja', desc = 'Physical blue magic can skillchain' },
    convergence      = { action = 'ja', spell = 'Convergence',            target = 'me', level = 75, main_only = true, group = 'ja', desc = 'Next magical spell +25% damage, single target' },
    diffusion        = { action = 'ja', spell = 'Diffusion',              target = 'me', level = 75, main_only = true, group = 'ja', desc = 'Next support spell >> party AoE' },
    efflux           = { action = 'ja', spell = 'Efflux',                 target = 'me', level = 83, main_only = true, group = 'ja', desc = 'Next physical spell +1000 TP bonus' },
    unbridledlearning = { action = 'ja', spell = 'Unbridled Learning',     target = 'me', level = 95, main_only = true, group = 'ja', desc = 'Cast NM-exclusive blue magic' },
    unbridledwisdom  = { action = 'ja', spell = 'Unbridled Wisdom',       target = 'me', level = 96, main_only = true, group = 'ja', desc = 'Cast Unbridled Learning spells' },

    -- ========================================================================
    -- BLUE MAGIC
    -- ========================================================================
    needles          = { action = 'ma', target = 'lastst', group = 'blue', desc = '1000 Needles',
                       tiers = { { spell = '1000 Needles', level = 62 } } },
    absoluteterror   = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Absolute Terror',
                       tiers = { { spell = 'Absolute Terror', level = 96 } } },
    acridstream      = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Acrid Stream',
                       tiers = { { spell = 'Acrid Stream', level = 77 } } },
    actinicburst     = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Actinic Burst',
                       tiers = { { spell = 'Actinic Burst', level = 74 } } },
    amorphicspikes   = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Amorphic Spikes',
                       tiers = { { spell = 'Amorphic Spikes', level = 98 } } },
    amplification    = { action = 'ma', target = 'me', group = 'blue', desc = 'Amplification',
                       tiers = { { spell = 'Amplification', level = 70 } } },
    animatingwail    = { action = 'ma', target = 'me', group = 'blue', desc = 'Animating Wail',
                       tiers = { { spell = 'Animating Wail', level = 79 } } },
    anvillightning   = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Anvil Lightning',
                       tiers = { { spell = 'Anvil Lightning', level = 99 } } },
    asuranclaws      = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Asuran Claws',
                       tiers = { { spell = 'Asuran Claws', level = 70 } } },
    atralibations    = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Atra. Libations',
                       tiers = { { spell = 'Atra. Libations', level = 99 } } },
    auroraldrape     = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Auroral Drape',
                       tiers = { { spell = 'Auroral Drape', level = 84 } } },
    awfuleye         = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Awful Eye',
                       tiers = { { spell = 'Awful Eye', level = 46 } } },
    badbreath        = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Bad Breath',
                       tiers = { { spell = 'Bad Breath', level = 61 } } },
    barbedcrescent   = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Barbed Crescent',
                       tiers = { { spell = 'Barbed Crescent', level = 99 } } },
    barriertusk      = { action = 'ma', target = 'me', group = 'blue', desc = 'Barrier Tusk',
                       tiers = { { spell = 'Barrier Tusk', level = 91 } } },
    batterycharge    = { action = 'ma', target = 'me', group = 'blue', desc = 'Battery Charge',
                       tiers = { { spell = 'Battery Charge', level = 79 } } },
    battledance      = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Battle Dance',
                       tiers = { { spell = 'Battle Dance', level = 12 } } },
    benthictyphoon   = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Benthic Typhoon',
                       tiers = { { spell = 'Benthic Typhoon', level = 83 } } },
    bilgestorm       = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Bilgestorm',
                       tiers = { { spell = 'Bilgestorm', level = 99 } } },
    blankgaze        = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Blank Gaze',
                       tiers = { { spell = 'Blank Gaze', level = 38 } } },
    blastbomb        = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Blastbomb',
                       tiers = { { spell = 'Blastbomb', level = 18 } } },
    blazingbound     = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Blazing Bound',
                       tiers = { { spell = 'Blazing Bound', level = 80 } } },
    blindingfulgor   = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Blinding Fulgor',
                       tiers = { { spell = 'Blinding Fulgor', level = 99 } } },
    blisteringroar   = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Blistering Roar',
                       tiers = { { spell = 'Blistering Roar', level = 99 } } },
    blitzstrahl      = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Blitzstrahl',
                       tiers = { { spell = 'Blitzstrahl', level = 44 } } },
    blooddrain       = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Blood Drain',
                       tiers = { { spell = 'Blood Drain', level = 20 } } },
    bloodsaber       = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Blood Saber',
                       tiers = { { spell = 'Blood Saber', level = 48 } } },
    bloodrake        = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Bloodrake',
                       tiers = { { spell = 'Bloodrake', level = 99 } } },
    bludgeon         = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Bludgeon',
                       tiers = { { spell = 'Bludgeon', level = 18 } } },
    bodyslam         = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Body Slam',
                       tiers = { { spell = 'Body Slam', level = 62 } } },
    bombtoss         = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Bomb Toss',
                       tiers = { { spell = 'Bomb Toss', level = 28 } } },
    cannonball       = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Cannonball',
                       tiers = { { spell = 'Cannonball', level = 70 } } },
    carcharianverve  = { action = 'ma', target = 'me', group = 'blue', desc = 'Carcharian Verve',
                       tiers = { { spell = 'Carcharian Verve', level = 99 } } },
    cesspool         = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Cesspool',
                       tiers = { { spell = 'Cesspool', level = 99 } } },
    chaoticeye       = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Chaotic Eye',
                       tiers = { { spell = 'Chaotic Eye', level = 32 } } },
    chargedwhisker   = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Charged Whisker',
                       tiers = { { spell = 'Charged Whisker', level = 88 } } },
    cimicinedischarge = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Cimicine Discharge',
                       tiers = { { spell = 'Cimicine Discharge', level = 78 } } },
    clawcyclone      = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Claw Cyclone',
                       tiers = { { spell = 'Claw Cyclone', level = 20 } } },
    cocoon           = { action = 'ma', target = 'me', group = 'blue', desc = 'Cocoon',
                       tiers = { { spell = 'Cocoon', level = 8 } } },
    coldwave         = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Cold Wave',
                       tiers = { { spell = 'Cold Wave', level = 52 } } },
    corrosiveooze    = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Corrosive Ooze',
                       tiers = { { spell = 'Corrosive Ooze', level = 66 } } },
    crashingthunder  = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Crashing Thunder',
                       tiers = { { spell = 'Crashing Thunder', level = 99 } } },
    crueljoke        = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Cruel Joke',
                       tiers = { { spell = 'Cruel Joke', level = 99 } } },
    cursedsphere     = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Cursed Sphere',
                       tiers = { { spell = 'Cursed Sphere', level = 18 } } },
    darkorb          = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Dark Orb',
                       tiers = { { spell = 'Dark Orb', level = 93 } } },
    deathray         = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Death Ray',
                       tiers = { { spell = 'Death Ray', level = 34 } } },
    deathscissors    = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Death Scissors',
                       tiers = { { spell = 'Death Scissors', level = 60 } } },
    deltathrust      = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Delta Thrust',
                       tiers = { { spell = 'Delta Thrust', level = 89 } } },
    demoralizingroar = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Demoralizing Roar',
                       tiers = { { spell = 'Demoralizing Roar', level = 80 } } },
    diamondhide      = { action = 'ma', target = 'me', group = 'blue', desc = 'Diamondhide',
                       tiers = { { spell = 'Diamondhide', level = 67 } } },
    diffusionray     = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Diffusion Ray',
                       tiers = { { spell = 'Diffusion Ray', level = 99 } } },
    digest           = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Digest',
                       tiers = { { spell = 'Digest', level = 36 } } },
    dimensionaldeath = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Dimensional Death',
                       tiers = { { spell = 'Dimensional Death', level = 60 } } },
    disseverment     = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Disseverment',
                       tiers = { { spell = 'Disseverment', level = 72 } } },
    dreamflower      = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Dream Flower',
                       tiers = { { spell = 'Dream Flower', level = 87 } } },
    droningwhirlwind = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Droning Whirlwind',
                       tiers = { { spell = 'Droning Whirlwind', level = 99 } } },
    embalmingearth   = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Embalming Earth',
                       tiers = { { spell = 'Embalming Earth', level = 99 } } },
    emptythrash      = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Empty Thrash',
                       tiers = { { spell = 'Empty Thrash', level = 87 } } },
    enervation       = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Enervation',
                       tiers = { { spell = 'Enervation', level = 67 } } },
    entomb           = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Entomb',
                       tiers = { { spell = 'Entomb', level = 99 } } },
    erraticflutter   = { action = 'ma', target = 'me', group = 'blue', desc = 'Erratic Flutter',
                       tiers = { { spell = 'Erratic Flutter', level = 99 } } },
    evryonegrudge    = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Evryone. Grudge',
                       tiers = { { spell = 'Evryone. Grudge', level = 90 } } },
    exuviation       = { action = 'ma', target = 'me', group = 'blue', desc = 'Exuviation',
                       tiers = { { spell = 'Exuviation', level = 75 } } },
    eyesonme         = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Eyes On Me',
                       tiers = { { spell = 'Eyes On Me', level = 61 } } },
    fantod           = { action = 'ma', target = 'me', group = 'blue', desc = 'Fantod',
                       tiers = { { spell = 'Fantod', level = 85 } } },
    featherbarrier   = { action = 'ma', target = 'me', group = 'blue', desc = 'Feather Barrier',
                       tiers = { { spell = 'Feather Barrier', level = 56 } } },
    featherstorm     = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Feather Storm',
                       tiers = { { spell = 'Feather Storm', level = 12 } } },
    feathertickle    = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Feather Tickle',
                       tiers = { { spell = 'Feather Tickle', level = 64 } } },
    filamentedhold   = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Filamented Hold',
                       tiers = { { spell = 'Filamented Hold', level = 52 } } },
    finalsting       = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Final Sting',
                       tiers = { { spell = 'Final Sting', level = 81 } } },
    firespit         = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Firespit',
                       tiers = { { spell = 'Firespit', level = 68 } } },
    flyinghippress   = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Flying Hip Press',
                       tiers = { { spell = 'Flying Hip Press', level = 58 } } },
    footkick         = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Foot Kick',
                       tiers = { { spell = 'Foot Kick', level = 1 } } },
    foulwaters       = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Foul Waters',
                       tiers = { { spell = 'Foul Waters', level = 99 } } },
    freneticrip      = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Frenetic Rip',
                       tiers = { { spell = 'Frenetic Rip', level = 63 } } },
    frightfulroar    = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Frightful Roar',
                       tiers = { { spell = 'Frightful Roar', level = 50 } } },
    frostbreath      = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Frost Breath',
                       tiers = { { spell = 'Frost Breath', level = 66 } } },
    frypan           = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Frypan',
                       tiers = { { spell = 'Frypan', level = 63 } } },
    gatesofhades     = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Gates of Hades',
                       tiers = { { spell = 'Gates of Hades', level = 97 } } },
    geistwall        = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Geist Wall',
                       tiers = { { spell = 'Geist Wall', level = 46 } } },
    glutinousdart    = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Glutinous Dart',
                       tiers = { { spell = 'Glutinous Dart', level = 99 } } },
    goblinrush       = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Goblin Rush',
                       tiers = { { spell = 'Goblin Rush', level = 81 } } },
    grandslam        = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Grand Slam',
                       tiers = { { spell = 'Grand Slam', level = 30 } } },
    hardenshell      = { action = 'ma', target = 'me', group = 'blue', desc = 'Harden Shell',
                       tiers = { { spell = 'Harden Shell', level = 95 } } },
    headbutt         = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Head Butt',
                       tiers = { { spell = 'Head Butt', level = 12 } } },
    healingbreeze    = { action = 'ma', target = 'me', group = 'blue', desc = 'Healing Breeze',
                       tiers = { { spell = 'Healing Breeze', level = 16 } } },
    heatbreath       = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Heat Breath',
                       tiers = { { spell = 'Heat Breath', level = 71 } } },
    heavystrike      = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Heavy Strike',
                       tiers = { { spell = 'Heavy Strike', level = 92 } } },
    hecatombwave     = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Hecatomb Wave',
                       tiers = { { spell = 'Hecatomb Wave', level = 54 } } },
    helldive         = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Helldive',
                       tiers = { { spell = 'Helldive', level = 16 } } },
    hydroshot        = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Hydro Shot',
                       tiers = { { spell = 'Hydro Shot', level = 63 } } },
    hystericbarrage  = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Hysteric Barrage',
                       tiers = { { spell = 'Hysteric Barrage', level = 69 } } },
    icebreak         = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Ice Break',
                       tiers = { { spell = 'Ice Break', level = 50 } } },
    infrasonics      = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Infrasonics',
                       tiers = { { spell = 'Infrasonics', level = 65 } } },
    jetstream        = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Jet Stream',
                       tiers = { { spell = 'Jet Stream', level = 38 } } },
    jettatura        = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Jettatura',
                       tiers = { { spell = 'Jettatura', level = 48 } } },
    leafstorm        = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Leafstorm',
                       tiers = { { spell = 'Leafstorm', level = 77 } } },
    lightofpenance   = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Light of Penance',
                       tiers = { { spell = 'Light of Penance', level = 58 } } },
    lowing           = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Lowing',
                       tiers = { { spell = 'Lowing', level = 71 } } },
    mpdrainkiss      = { action = 'ma', target = 'lastst', group = 'blue', desc = 'MP Drainkiss',
                       tiers = { { spell = 'MP Drainkiss', level = 42 } } },
    maelstrom        = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Maelstrom',
                       tiers = { { spell = 'Maelstrom', level = 61 } } },
    magicbarrier     = { action = 'ma', target = 'me', group = 'blue', desc = 'Magic Barrier',
                       tiers = { { spell = 'Magic Barrier', level = 82 } } },
    magicfruit       = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Magic Fruit',
                       tiers = { { spell = 'Magic Fruit', level = 58 } } },
    magichammer      = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Magic Hammer',
                       tiers = { { spell = 'Magic Hammer', level = 74 } } },
    magnetitecloud   = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Magnetite Cloud',
                       tiers = { { spell = 'Magnetite Cloud', level = 46 } } },
    mandibularbite   = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Mandibular Bite',
                       tiers = { { spell = 'Mandibular Bite', level = 44 } } },
    mementomori      = { action = 'ma', target = 'me', group = 'blue', desc = 'Memento Mori',
                       tiers = { { spell = 'Memento Mori', level = 62 } } },
    metallicbody     = { action = 'ma', target = 'me', group = 'blue', desc = 'Metallic Body',
                       tiers = { { spell = 'Metallic Body', level = 8 } } },
    mightyguard      = { action = 'ma', target = 'me', group = 'blue', desc = 'Mighty Guard',
                       tiers = { { spell = 'Mighty Guard', level = 99 } } },
    mindblast        = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Mind Blast',
                       tiers = { { spell = 'Mind Blast', level = 73 } } },
    moltingplumage   = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Molting Plumage',
                       tiers = { { spell = 'Molting Plumage', level = 99 } } },
    mortalray        = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Mortal Ray',
                       tiers = { { spell = 'Mortal Ray', level = 91 } } },
    mysteriouslight  = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Mysterious Light',
                       tiers = { { spell = 'Mysterious Light', level = 40 } } },
    nectarousdeluge  = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Nectarous Deluge',
                       tiers = { { spell = 'Nectarous Deluge', level = 99 } } },
    ocounterstance   = { action = 'ma', target = 'me', group = 'blue', desc = 'O. Counterstance',
                       tiers = { { spell = 'O. Counterstance', level = 98 } } },
    occultation      = { action = 'ma', target = 'me', group = 'blue', desc = 'Occultation',
                       tiers = { { spell = 'Occultation', level = 88 } } },
    osmosis          = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Osmosis',
                       tiers = { { spell = 'Osmosis', level = 84 } } },
    pallingsalvo     = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Palling Salvo',
                       tiers = { { spell = 'Palling Salvo', level = 99 } } },
    paralyzingtriad  = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Paralyzing Triad',
                       tiers = { { spell = 'Paralyzing Triad', level = 99 } } },
    pineconebomb     = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Pinecone Bomb',
                       tiers = { { spell = 'Pinecone Bomb', level = 36 } } },
    plasmacharge     = { action = 'ma', target = 'me', group = 'blue', desc = 'Plasma Charge',
                       tiers = { { spell = 'Plasma Charge', level = 75 } } },
    pleniluneembrace = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Plenilune Embrace',
                       tiers = { { spell = 'Plenilune Embrace', level = 76 } } },
    poisonbreath     = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Poison Breath',
                       tiers = { { spell = 'Poison Breath', level = 22 } } },
    polarroar        = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Polar Roar',
                       tiers = { { spell = 'Polar Roar', level = 99 } } },
    pollen           = { action = 'ma', target = 'me', group = 'blue', desc = 'Pollen',
                       tiers = { { spell = 'Pollen', level = 1 } } },
    powerattack      = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Power Attack',
                       tiers = { { spell = 'Power Attack', level = 4 } } },
    pyricbulwark     = { action = 'ma', target = 'me', group = 'blue', desc = 'Pyric Bulwark',
                       tiers = { { spell = 'Pyric Bulwark', level = 98 } } },
    quadcontinuum    = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Quad. Continuum',
                       tiers = { { spell = 'Quad. Continuum', level = 85 } } },
    quadrastrike     = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Quadrastrike',
                       tiers = { { spell = 'Quadrastrike', level = 96 } } },
    queasyshroom     = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Queasyshroom',
                       tiers = { { spell = 'Queasyshroom', level = 8 } } },
    radiantbreath    = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Radiant Breath',
                       tiers = { { spell = 'Radiant Breath', level = 54 } } },
    railcannon       = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Rail Cannon',
                       tiers = { { spell = 'Rail Cannon', level = 99 } } },
    ramcharge        = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Ram Charge',
                       tiers = { { spell = 'Ram Charge', level = 73 } } },
    reactorcool      = { action = 'ma', target = 'me', group = 'blue', desc = 'Reactor Cool',
                       tiers = { { spell = 'Reactor Cool', level = 74 } } },
    reavingwind      = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Reaving Wind',
                       tiers = { { spell = 'Reaving Wind', level = 90 } } },
    refueling        = { action = 'ma', target = 'me', group = 'blue', desc = 'Refueling',
                       tiers = { { spell = 'Refueling', level = 48 } } },
    regeneration     = { action = 'ma', target = 'me', group = 'blue', desc = 'Regeneration',
                       tiers = { { spell = 'Regeneration', level = 78 } } },
    regurgitation    = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Regurgitation',
                       tiers = { { spell = 'Regurgitation', level = 69 } } },
    rendingdeluge    = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Rending Deluge',
                       tiers = { { spell = 'Rending Deluge', level = 99 } } },
    restoral         = { action = 'ma', target = 'me', group = 'blue', desc = 'Restoral',
                       tiers = { { spell = 'Restoral', level = 99 } } },
    retinalglare     = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Retinal Glare',
                       tiers = { { spell = 'Retinal Glare', level = 99 } } },
    salinecoat       = { action = 'ma', target = 'me', group = 'blue', desc = 'Saline Coat',
                       tiers = { { spell = 'Saline Coat', level = 72 } } },
    sandspin         = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Sandspin',
                       tiers = { { spell = 'Sandspin', level = 1 } } },
    sandspray        = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Sandspray',
                       tiers = { { spell = 'Sandspray', level = 66 } } },
    saurianslide     = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Saurian Slide',
                       tiers = { { spell = 'Saurian Slide', level = 99 } } },
    scouringspate    = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Scouring Spate',
                       tiers = { { spell = 'Scouring Spate', level = 99 } } },
    screwdriver      = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Screwdriver',
                       tiers = { { spell = 'Screwdriver', level = 26 } } },
    searingtempest   = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Searing Tempest',
                       tiers = { { spell = 'Searing Tempest', level = 99 } } },
    seedspray        = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Seedspray',
                       tiers = { { spell = 'Seedspray', level = 61 } } },
    selfdestruct     = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Self-Destruct',
                       tiers = { { spell = 'Self-Destruct', level = 50 } } },
    sheepsong        = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Sheep Song',
                       tiers = { { spell = 'Sheep Song', level = 16 } } },
    sickleslash      = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Sickle Slash',
                       tiers = { { spell = 'Sickle Slash', level = 48 } } },
    silentstorm      = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Silent Storm',
                       tiers = { { spell = 'Silent Storm', level = 99 } } },
    sinkerdrill      = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Sinker Drill',
                       tiers = { { spell = 'Sinker Drill', level = 99 } } },
    smiteofrage      = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Smite of Rage',
                       tiers = { { spell = 'Smite of Rage', level = 34 } } },
    soporific        = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Soporific',
                       tiers = { { spell = 'Soporific', level = 24 } } },
    soundblast       = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Sound Blast',
                       tiers = { { spell = 'Sound Blast', level = 32 } } },
    spectralfloe     = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Spectral Floe',
                       tiers = { { spell = 'Spectral Floe', level = 99 } } },
    spinalcleave     = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Spinal Cleave',
                       tiers = { { spell = 'Spinal Cleave', level = 63 } } },
    spiralspin       = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Spiral Spin',
                       tiers = { { spell = 'Spiral Spin', level = 60 } } },
    sproutsmack      = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Sprout Smack',
                       tiers = { { spell = 'Sprout Smack', level = 4 } } },
    stinkinggas      = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Stinking Gas',
                       tiers = { { spell = 'Stinking Gas', level = 44 } } },
    subzerosmash     = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Sub-zero Smash',
                       tiers = { { spell = 'Sub-zero Smash', level = 72 } } },
    subduction       = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Subduction',
                       tiers = { { spell = 'Subduction', level = 99 } } },
    suddenlunge      = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Sudden Lunge',
                       tiers = { { spell = 'Sudden Lunge', level = 95 } } },
    sweepinggouge    = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Sweeping Gouge',
                       tiers = { { spell = 'Sweeping Gouge', level = 99 } } },
    tailslap         = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Tail Slap',
                       tiers = { { spell = 'Tail Slap', level = 69 } } },
    tearinggust      = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Tearing Gust',
                       tiers = { { spell = 'Tearing Gust', level = 99 } } },
    temupheaval      = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Tem. Upheaval',
                       tiers = { { spell = 'Tem. Upheaval', level = 99 } } },
    temporalshift    = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Temporal Shift',
                       tiers = { { spell = 'Temporal Shift', level = 73 } } },
    tenebralcrush    = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Tenebral Crush',
                       tiers = { { spell = 'Tenebral Crush', level = 99 } } },
    terrortouch      = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Terror Touch',
                       tiers = { { spell = 'Terror Touch', level = 40 } } },
    thermalpulse     = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Thermal Pulse',
                       tiers = { { spell = 'Thermal Pulse', level = 86 } } },
    thrashingassault = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Thrashing Assault',
                       tiers = { { spell = 'Thrashing Assault', level = 99 } } },
    thunderbreath    = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Thunder Breath',
                       tiers = { { spell = 'Thunder Breath', level = 97 } } },
    thunderbolt      = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Thunderbolt',
                       tiers = { { spell = 'Thunderbolt', level = 95 } } },
    tourbillion      = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Tourbillion',
                       tiers = { { spell = 'Tourbillion', level = 97 } } },
    triumphantroar   = { action = 'ma', target = 'me', group = 'blue', desc = 'Triumphant Roar',
                       tiers = { { spell = 'Triumphant Roar', level = 71 } } },
    uppercut         = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Uppercut',
                       tiers = { { spell = 'Uppercut', level = 38 } } },
    uproot           = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Uproot',
                       tiers = { { spell = 'Uproot', level = 99 } } },
    vanitydive       = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Vanity Dive',
                       tiers = { { spell = 'Vanity Dive', level = 82 } } },
    vaporspray       = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Vapor Spray',
                       tiers = { { spell = 'Vapor Spray', level = 96 } } },
    venomshell       = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Venom Shell',
                       tiers = { { spell = 'Venom Shell', level = 42 } } },
    verticalcleave   = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Vertical Cleave',
                       tiers = { { spell = 'Vertical Cleave', level = 75 } } },
    voracioustrunk   = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Voracious Trunk',
                       tiers = { { spell = 'Voracious Trunk', level = 64 } } },
    warmup           = { action = 'ma', target = 'me', group = 'blue', desc = 'Warm-Up',
                       tiers = { { spell = 'Warm-Up', level = 68 } } },
    waterbomb        = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Water Bomb',
                       tiers = { { spell = 'Water Bomb', level = 92 } } },
    whirlofrage      = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Whirl of Rage',
                       tiers = { { spell = 'Whirl of Rage', level = 83 } } },
    whitewind        = { action = 'ma', target = 'me', group = 'blue', desc = 'White Wind',
                       tiers = { { spell = 'White Wind', level = 94 } } },
    wildcarrot       = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Wild Carrot',
                       tiers = { { spell = 'Wild Carrot', level = 30 } } },
    wildoats         = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Wild Oats',
                       tiers = { { spell = 'Wild Oats', level = 4 } } },
    windbreath       = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Wind Breath',
                       tiers = { { spell = 'Wind Breath', level = 99 } } },
    windsofpromy     = { action = 'ma', target = 'me', group = 'blue', desc = 'Winds of Promy.',
                       tiers = { { spell = 'Winds of Promy.', level = 89 } } },
    yawn             = { action = 'ma', target = 'lastst', group = 'blue', desc = 'Yawn',
                       tiers = { { spell = 'Yawn', level = 64 } } },
    zephyrmantle     = { action = 'ma', target = 'me', group = 'blue', desc = 'Zephyr Mantle',
                       tiers = { { spell = 'Zephyr Mantle', level = 65 } } },
}

return M
